In [72]:
import pandas as pd
import numpy as np
df = pd.read_csv("../Raw data/imdb_top_1000.csv")

In [73]:
print(df.isnull().sum())

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [74]:
df=(df.dropna())
print(df)

                                           Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...
..                                                 ...
990  https://m.media-amazon.com/images/M/MV5BYjRmY2...
991  https://m.media-amazon.com/images/M/MV5BMzAyND...
992  https://m.media-amazon.com/images/M/MV5BMjAwMT...
994  https://m.media-amazon.com/images/M/MV5BZjQyMG...
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min
1               The Godfather          1972           A  175 min
2             The Dark Knight          2008          UA  152 min
3      The Godfather: Part II          1974           A  202 min
4                12 Angry Men          1957           U   96 min
..                        ...           ...         ...      ...
990              Giù la testa          1971          PG  157 min
991            Kelly's Heroes          1970          GP  144 min
992           The Jungle Book          1967           U   78 min
994        A Hard Day's Night          1964           U   87 min
997     From Here to Eternity          1953      Passed  118 min

                            Genre  IMDB_Rating  \
0                           Drama          9.3
1                    Crime, Drama          9.2
2            Action, Crime, Drama          9.0
3                    Crime, Drama          9.0
4                    Crime, Drama          9.0
..                            ...          ...
990           Drama, War, Western          7.6
991        Adventure, Comedy, War          7.6
992  Animation, Adventure, Family          7.6
994        Comedy, Music, Musical          7.6
997           Drama, Romance, War          7.6

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0
1    An organized crime dynasty's aging patriarch t...       100.0
2    When the menace known as the Joker wreaks havo...        84.0
3    The early life and career of Vito Corleone in ...        90.0
4    A jury holdout attempts to prevent a miscarria...        96.0
..                                                 ...         ...
990  A low-life bandit and an I.R.A. explosives exp...        77.0
991  A group of U.S. soldiers sneaks across enemy l...        50.0
992  Bagheera the Panther and Baloo the Bear have a...        65.0
994  Over two "typical" days in the life of The Bea...        96.0
997  In Hawaii in 1941, a private is cruelly punish...        85.0

                 Director           Star1             Star2            Star3  \
0          Frank Darabont     Tim Robbins    Morgan Freeman       Bob Gunton
1    Francis Ford Coppola   Marlon Brando         Al Pacino       James Caan
2       Christopher Nolan  Christian Bale      Heath Ledger    Aaron Eckhart
3    Francis Ford Coppola       Al Pacino    Robert De Niro    Robert Duvall
4            Sidney Lumet     Henry Fonda       Lee J. Cobb    Martin Balsam
..                    ...             ...               ...              ...
990          Sergio Leone     Rod Steiger      James Coburn     Romolo Valli
991       Brian G. Hutton  Clint Eastwood     Telly Savalas      Don Rickles
992   Wolfgang Reitherman     Phil Harris   Sebastian Cabot      Louis Prima
994        Richard Lester     John Lennon    Paul McCartney  George Harrison
997        Fred Zinnemann  Burt Lancaster  Montgomery Clift     Deborah Kerr

                Star4  No_of_Votes        Gross
0      William Sadler      2343110   28,341,469
1        Diane Keaton      1620367  134,966,411
2       Michael Caine      2303232  534,858,444
3        Diane Keaton      1129952   57,300,000
4        John Fiedler       689845    4,360,000
..                ...          ...          ...
990       Maria Monti        30144      696,690
991  Carroll O'Connor        45338    1,378,435
992  Bruce Reitherman       166409  141,843,612
994       Ringo Starr        40351   13,780,024
997        Donna Reed        43374   30,500,000

[714 rows x 16 columns]

In [75]:
print(df.isnull().sum())

Poster_Link      0
Series_Title     0
Released_Year    0
Certificate      0
Runtime          0
Genre            0
IMDB_Rating      0
Overview         0
Meta_score       0
Director         0
Star1            0
Star2            0
Star3            0
Star4            0
No_of_Votes      0
Gross            0
dtype: int64

In [76]:
df.shape

(714, 16)

In [77]:
print(df.duplicated().sum())

0

In [78]:
df.dtypes

Poster_Link          str
Series_Title         str
Released_Year        str
Certificate          str
Runtime              str
Genre                str
IMDB_Rating      float64
Overview             str
Meta_score       float64
Director             str
Star1                str
Star2                str
Star3                str
Star4                str
No_of_Votes        int64
Gross                str
dtype: object

In [79]:
#issues with runtime- int, released yr- int, runtime- int, gross- remove commas
df["Released_Year"].unique()

<StringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2019', '2014', '1998',
 '1997', '1995', '1991', '1977', '1954', '2011', '2006', '2000', '1988',
 '1985', '1968', '1960', '1942', '1936', '1931', '2018', '2016', '2017',
 '2012', '2009', '1981', '1979', '1964', '2004', '1992', '1987', '1986',
 '1984', '1983', '1976', '1973', '1971', '1965', '1962', '1959', '1958',
 '1952', '1944', '1941', '2013', '2007', '2005', '1989', '1963', '1950',
 '1948', '2015', '1996', '1982', '1978', '1967', '1951', '1949', '1940',
 '1939', '1934', '1970', '1969', '1961', '1946', '1930', '1938', '1933',
   'PG', '1953']
Length: 83, dtype: str

In [80]:
#to find the problem- 
df[~df["Released_Year"].str.isnumeric()]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [81]:
#correct the value
df.loc[df["Released_Year"]=="PG", "Released_Year"]="1995"
df[df["Series_Title"]=="Apollo 13"]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,1995,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [82]:
#change dtype
df["Released_Year"]= df["Released_Year"].astype(int)
print(df["Released_Year"].dtype)

int64

In [83]:
type(df)

pandas.DataFrame

In [84]:
df["Runtime"] = df["Runtime"].str.replace(" min", "", regex=False)

In [85]:
df["Runtime"].head

<bound method NDFrame.head of 0      142
1      175
2      152
3      202
4       96
      ...
990    157
991    144
992     78
994     87
997    118
Name: Runtime, Length: 714, dtype: str>

In [86]:
df["Runtime"] = df["Runtime"].astype(int)

In [87]:
df["Gross"]= df["Gross"].str.replace(",","", regex=False)
df["Gross"].head(2)

0     28341469
1    134966411
Name: Gross, dtype: str

In [88]:
df["Gross"] = df["Gross"].astype(int)

In [89]:
df.to_csv("../Data/Cleaned data/imdb_cleaned.csv", index=False)

In [92]:
print(df.shape)
print(df["Gross"].isna().sum())
print(df["Gross"].dtype)

(714, 16)
0
int64